FROM mcr.microsoft.com/vscode/devcontainers/go:0-1.18-bullseye

# [Optional] Uncomment this section to install additional OS packages.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends unixodbc unixodbc-dev

# COPY IBMInformixODBCDriverforUnix.deb /tmp/IBMInformixODBCDriverforUnix.deb
# RUN dpkg -i /tmp/IBMInformixODBCDriverforUnix.deb

# [Optional] Uncomment the next line to use go get to install anything else you need
# RUN go get -x github.com/ibmdb/go-informix
